"""
===========================================================================
Batch Builder
===========================================================================

Constructs Batch objects from optimized product groups generated by the
Batch Optimizer.

Responsibilities
----------------
1. Generate unique batch identifiers.
2. Convert optimized product groups into Batch objects.
3. Populate batch metadata.
4. Return candidate batches for Stage-2 dispatch optimization.

This module intentionally contains no optimization logic.
===========================================================================
"""

from datetime import datetime

from .batch import Batch


class BatchBuilder:
    """
    Builds Batch objects from optimized product groups.
    """

    # ------------------------------------------------------------------ #
    # Public API
    # ------------------------------------------------------------------ #

    def build_batches(self, optimized_groups):
        """
        Build Batch objects.

        Parameters
        ----------
        optimized_groups : list[dict]
            Output from BatchOptimizer.

        Returns
        -------
        list[Batch]
        """

        batches = []

        if not optimized_groups:
            return []

        for group in optimized_groups:
            batch = self._create_batch(group)
            batches.append(batch)

        return batches

    # ------------------------------------------------------------------ #
    # Private Methods
    # ------------------------------------------------------------------ #

    def _create_batch(self, group):
        """
        Create a Batch object from one optimized group.
        """

        if not products:
            raise ValueError("Optimized group contains no products.")
        
        products = group["products"]

        total_units = sum(
            p["normalized_units"]
            for p in products
        )

        required = (
            "dispatch_center",
            "destination_zone",
            "products",
        )

        for key in required:
            if key not in group:
                raise KeyError(f"Missing '{key}' in optimized group.")

        return Batch(
            batch_id=self._generate_batch_id(),
            dispatch_center=group["dispatch_center"],
            destination_zone=group["destination_zone"],
            products=products,
            batch_size=total_units,
            creation_time=datetime.now(),
        )

    def _generate_batch_id(self):
        """
        Generate a unique batch identifier.
        """

        return (
            "BAT-"
            + datetime.now().strftime("%Y%m%d%H%M%S%f")
        )