"""
===============================================================
ZONE ASSIGNMENT VALIDATOR
===============================================================

Validates the output generated by the Zone Assignment Optimizer.

Responsibilities
----------------
1. Ensure each driver is assigned only once.
2. Ensure each operational zone has one driver.
3. Ensure assigned drivers are available.
4. Ensure familiarity scores are valid.
5. Ensure no missing values exist.

This module performs validation only.
It does not modify assignments.

===============================================================
"""

import pandas as pd

from .config import MIN_FAMILIARITY_THRESHOLD


class ZoneAssignmentValidator:
    """Validates Zone Assignment results."""

    def __init__(
        self,
        assignments: pd.DataFrame,
        available_drivers: pd.DataFrame
    ):

        self.assignments = assignments.copy()
        self.available_drivers = available_drivers.copy()

    # ==========================================================
    # Public API
    # ==========================================================

    def validate(self):

        self._check_required_columns()
        self._check_missing_values()
        self._check_duplicate_drivers()
        self._check_duplicate_zones()
        self._check_driver_availability()
        self._check_familiarity()

        return True

    # ==========================================================
    # Required Columns
    # ==========================================================

    def _check_required_columns(self):

        required = [
            "driver_id",
            "zone_id",
            "familiarity_score"
        ]

        missing = set(required) - set(self.assignments.columns)

        if missing:
            raise ValueError(
                f"Missing columns: {sorted(missing)}"
            )

    # ==========================================================
    # Missing Values
    # ==========================================================

    def _check_missing_values(self):

        if self.assignments.isnull().any().any():

            raise ValueError(
                "Assignment contains missing values."
            )

    # ==========================================================
    # Duplicate Drivers
    # ==========================================================

    def _check_duplicate_drivers(self):

        duplicates = self.assignments[
            self.assignments.duplicated(
                subset="driver_id",
                keep=False
            )
        ]

        if not duplicates.empty:

            raise ValueError(
                "Driver assigned to multiple zones."
            )

    # ==========================================================
    # Duplicate Zones
    # ==========================================================

    def _check_duplicate_zones(self):

        duplicates = self.assignments[
            self.assignments.duplicated(
                subset="zone_id",
                keep=False
            )
        ]

        if not duplicates.empty:

            raise ValueError(
                "Zone assigned multiple drivers."
            )

    # ==========================================================
    # Driver Availability
    # ==========================================================

    def _check_driver_availability(self):

        if "driver_id" not in self.available_drivers.columns:
            raise ValueError(
                "available_drivers must contain 'driver_id'."
            )

        available = set(
            self.available_drivers["driver_id"]
        )

        assigned = set(
            self.assignments["driver_id"]
        )

        unavailable = assigned - available

        if unavailable:

            raise ValueError(
                f"Unavailable drivers assigned: "
                f"{sorted(unavailable)}"
            )

    # ==========================================================
    # Familiarity Score
    # ==========================================================

    def _check_familiarity(self):

        if (
            self.assignments["familiarity_score"] < 0
        ).any():

            raise ValueError(
                "Negative familiarity score detected."
            )

        if (
            self.assignments["familiarity_score"] > 1
        ).any():

            raise ValueError(
                "Familiarity score exceeds 1."
            )

        low_scores = self.assignments[
            self.assignments["familiarity_score"]
            < MIN_FAMILIARITY_THRESHOLD
        ]

        if not low_scores.empty:

            print(
                "\nWARNING: "
                f"{len(low_scores)} assignments have "
                "very low familiarity."
            )

    # ==========================================================
    # Summary
    # ==========================================================

    def summary(self):

        return {
            "Assignments": len(self.assignments),
            "Drivers": self.assignments["driver_id"].nunique(),
            "Zones": self.assignments["zone_id"].nunique(),
            "Average Familiarity": round(
                self.assignments["familiarity_score"].mean(),
                4
            ),
            "Minimum Familiarity": round(
                self.assignments["familiarity_score"].min(),
                4
            ),
            "Maximum Familiarity": round(
                self.assignments["familiarity_score"].max(),
                4
            )
        }